### ISSUE TITLE
Updated schema?

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/open-certificate#13]
Hi,

Is this the updated schema? I saw NP's sample cert under the transcript (array) and they're using programDescription & semester objects.

**Comment by yehjxraymond** [comment]
The schema is updated. Schools can add more fields if they like to as long as they conform to the basic structure. To test your data against the schema, you can use tools like: https://www.jsonschemavalidator.net/

**Comment by yehjxraymond** [comment]
You may copy the json schema from https://github.com/OpenCerts/open-certificate/blob/master/schema/1.4/schema.json to the left of the tool to test against it.
