### ISSUE TITLE
Issuing certificate

### ISSUE THREAD

**Issue by WillVill** [OpenCerts/open-certificate#202]
Hi,

I am a little confused with the documentation, mainly 2 things: 
1) Where am I connecting openCert to my ETH address?
2) The issueCertificate function, does not actually issue a certificate if I understand it right? It adds a signature to the certificate? Or am I getting this totally wrong? I can see it calls issueDocument from Open Attestation but that function does not seem to be exported from there either?

This is what I have gotten so far. The "connect" function returns a connected instance of document-store to my ETH wallet via private key. I am a little confused by the documentation or lack thereof.

```
const openCert = require('@govtechsg/open-certificate');
const connect = require('./connect');

const issueCert = async (cert, recipient) => {
    const documentStore = connect();
    const formattedCert = formatCert(cert, recipient);

    const signedCert = openCert.issueCertificate(formattedCert)
    const tx = documentStore.issue(signedCert) // Supposed to issue merkle root?
    const receipt = await tx.wait();

    console.log('receipt', receipt);
};
```

**Comment by Nebulis** [comment]
Hi,

How did you find across this repo? The documentation doesn't mention it and target lead you to open attestation documentation (https://docs.opencerts.io/docs/).

I don't recommend to use this repo. 

```
The issueCertificate function, does not actually issue a certificate if I understand it right? It adds a signature to the certificate?
```
You are right and this is very confusing. The issue fibrin in this repo is what we call `wrap` process in open attestation. It just prepare your document for real issuance.

**Comment by WillVill** [comment]
Hi Nebulis,

Thanks for the quick reply. Ok I will stick to open-attestation. This is the first opencerts library/docs I found via google and I believe that is where my confusion originally started.
