### ISSUE TITLE
"OpenCerts 2.0 DNS-TXT Verification" schema updates?

### ISSUE THREAD

**Issue by pranavburnwal** [OpenCerts/open-certificate#46]
Hi OC Team,

The schema changes listed under 
https://docs.opencerts.io/announcements/schema2_update.html
for DNS TXT Record. When can be expected to be updated?

Thanks!

**Comment by rjchow** [comment]
already implemented

**Comment by pranavburnwal** [comment]
Thanks for replying.

So the value in issuers saving the store address will be called "certificateStore" or "documentStore"?
Or we need to keep both?

**Comment by rjchow** [comment]
documentStore

**Comment by pranavburnwal** [comment]
Thanks!
