### ISSUE TITLE
issueCertificates method taking a lot of time when signing Bulk OpenCerts 

### ISSUE THREAD

**Issue by ssgwsg-acn** [OpenCerts/open-certificate#48]
Hi Team, 

We have observed that during signing the OpenCerts with NPM module the issueCertifiacates function is taking very long to Sign the JSON files if we sign bulk OpenCerts.

For example:  
4,000 Certs take around 30 Min max 
But when we sign bulk certificates like:
40,000 Certs it will take around 12 to 13 hours (we expected it to finish 5hr time based on 4K records estimations)

So what we looking for is :
1. Small batches finish faster compare with bulk, is there any new version publish that we can use? 
2. How much is max certs we can sign in single go?

If you have any other suggestions please let us know.

**Comment by Nebulis** [comment]
Hi, which version did you use ?

**Comment by ssgwsg-acn** [comment]
Hi, we are using 1.1.38 @govtechsg/open-certificate

**Comment by Nebulis** [comment]
1. Could you try to upgrade to the latest version available ?
2. Why is the time taken an issue for you ?

```
How much is max certs we can sign in single go?
```
There is no limit as such, it will be limited by the memory.

**Comment by ssgwsg-acn** [comment]
1. Thanks will try to update with latest version but it will support 1.5 Version JSON?
2. We are running this cert generation daily for history migration of all old ecerts to OpenCerts and daily we want to finish as much as possible.

**Comment by Nebulis** [comment]
Yes it supports v1.5. Please let us know once you tried with latest version.
