### ISSUE TITLE
multiple certificate stores on a single domain?

### ISSUE THREAD

**Issue by wmclaxton** [OpenCerts/open-certificate#63]
My cert does not verify - https://issuer-qa.nextid.com/certificate?id=08a26ad9-108d-479f-b11b-4d8a11da8b55.

Unlike CNAMEs, TXT records are associated with domain not hostname or FQDN.  Is there any reason that we cannot have multiple subdomains, each with its own certificate store, and each being verified using its own TXT record?  In other words, can we have multiple TXT records associated with same domain?

Example: 
nextid.com. | 900 | IN | TXT | openatts net=ethereum netId=1 addr=0xa6C85039106374b92851ec5d9085d757875ac6E3

nextid.com. | 300 | IN | TXT | openatts net=ethereum netId=1 addr=0x8636477eE364827a2e12fC3923213B84DE60b1C2

**Comment by rjchow** [comment]
hi bill i'm not too sure what's the specific issue you're raising?

there shouldn't be any trouble with having multiple TXT records on your subdomain - we actually have multiple records both on subdomains and root domains and they've worked fine

one issue I noticed is that your records are on nextid.com whereas in your document they're on issuer-qa.nextid.com - these need to match for it to work

```
> q.getDocumentStoreRecords("issuer-qa.nextid.com").then(console.log)
> []

> q.getDocumentStoreRecords("nextid.com").then(console.log)
> [ { type: 'openatts',
    net: 'ethereum',
    netId: '1',
    addr: '0xa6C85039106374b92851ec5d9085d757875ac6E3',
    dnssec: false },
  { type: 'openatts',
    net: 'ethereum',
    netId: '1',
    addr: '0x0F730154d6fb76E7E8BdE88eFAED2Fe0372eDAB8',
    dnssec: false },
  { type: 'openatts',
    net: 'ethereum',
    netId: '1',
    addr: '0x8636477eE364827a2e12fC3923213B84DE60b1C2',
    dnssec: false } ]
```

**Comment by rjchow** [comment]
also use "documentStore" instead of "certificateStore" in the issuer object

**Comment by wmclaxton** [comment]
Thank you Raymond, esp for clarification about DNS records.  Will see how to fix this asap, then close the case.
