### ISSUE TITLE
Identifier for OpenCert 1.5/2.0

### ISSUE THREAD

**Issue by P1312120** [OpenCerts/open-certificate#84]
Hi, may I know is there any identifier that's able to indicate that this particular OpenCert belongs to schema 1.5 / 2.0 ?

**Comment by Nebulis** [comment]
![image](https://user-images.githubusercontent.com/503185/76706033-861e4800-671f-11ea-9f4b-968ea0f98add.png)
schema ? :)

**Comment by P1312120** [comment]
Hi Nebulis, thanks for your fast response. =)
Opsss, it's not provided in the schema 2.0 section.

![image](https://user-images.githubusercontent.com/33021426/76733565-05e9f800-679c-11ea-86ff-12af6035a2af.png)

Seems like this field is not mandatory too..
![image](https://user-images.githubusercontent.com/33021426/76733692-48133980-679c-11ea-9afb-53a5734c8219.png)

For the valid OpenCert without schema field, how're we gonna identity that particular OpenCert belongs to 11.5 / 2.0 ??

Thanks!

**Comment by Nebulis** [comment]
The schema is about the data coming in, not for the outputted data. The schema property is populated with the schema id you used to wrap the file
